export const brand = {
  name: "Céleste",
  fullName: "Maison Céleste",
  tagline: "Luxury Hair. Timeless Style.",
  email: "info@maisonceleste.com",
  phone: "+39 02 8765 4321",
  phoneHref: "+390287654321",
  whatsapp: "390287654321",
  address: "Via Montenapoleone 12, 20121 Milano, Italy",
  hours: "Tue–Sat 09:30–20:00 · Closed Sun–Mon",
  instagram: "https://instagram.com/maisonceleste",
  facebook: "https://facebook.com/maisonceleste",
  tiktok: "https://tiktok.com/@maisonceleste",
  linkedin: "https://linkedin.com/company/maisonceleste",
  mapsEmbed:
    "https://maps.google.com/maps?q=Via+Montenapoleone+12,+Milan&t=&z=15&ie=UTF8&iwloc=&output=embed",
} as const;

/** Custom-generated salon imagery stored in /public/images */
export const images = {
  hero: "/images/hero/hero-salon.png",
  haircut: "/images/services/service-haircut.png",
  balayage: "/images/services/service-balayage.png",
  coloring: "/images/services/service-coloring.png",
  highlights: "/images/services/service-highlights.png",
  extensions: "/images/services/service-extensions.png",
  bridal: "/images/services/service-bridal.png",
  keratin: "/images/services/service-keratin.png",
  botox: "/images/services/service-botox.png",
  blowdry: "/images/services/service-blowdry.png",
  scalp: "/images/services/service-scalp.png",
  spa: "/images/services/service-spa.png",
  interior: "/images/services/salon-interior.png",
  styling: "/images/services/service-styling.png",
  stylist: "/images/services/professional-stylist.png",
  artist1: "/images/services/professional-stylist.png",
  artist2: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&w=800&q=80",
  artist3: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80",
  artist4: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=800&q=80",
  artist5: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80",
  artist6: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=800&q=80",
  artist7: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80",
  artist8: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80",
  splitHaircut: "/images/transformations/split-haircut.png",
  splitBalayage: "/images/transformations/split-balayage.png",
  splitColorCorrection: "/images/transformations/split-color-correction.png",
  splitExtensions: "/images/transformations/split-extensions.png",
  splitKeratin: "/images/transformations/split-keratin.png",
  splitBotox: "/images/transformations/split-botox.png",
  client1: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80",
  client2: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=200&q=80",
  client3: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
  client4: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80",
  ig1: "/images/services/service-balayage.png",
  ig2: "/images/services/service-haircut.png",
  ig3: "/images/services/service-highlights.png",
  ig4: "/images/services/service-extensions.png",
  ig5: "/images/services/service-bridal.png",
  ig6: "/images/hero/hero-salon.png",
} as const;

export const stylists = [
  "Any Available Stylist",
  "Isabella Conti — Master Hair Stylist",
  "Marco Bellini — Creative Director",
  "Elena Rossi — Senior Color Specialist",
  "Sofia Marchetti — Balayage Expert",
  "Giulia Ferraro — Extension Specialist",
  "Chiara Romano — Keratin Specialist",
  "Lucia Bianchi — Bridal Hair Artist",
  "Anna Greco — Scalp Care Expert",
] as const;

export const serviceOptions = [
  "Luxury Haircut",
  "Balayage",
  "Hair Coloring",
  "Hair Extensions",
  "Keratin Treatment",
  "Hair Botox",
  "Luxury Blow Dry",
  "Bridal Hairstyling",
  "Scalp Treatment",
  "Luxury Hair Spa",
  "Hair Consultation",
] as const;
